@startuml
class Shape  
class SPHBody{
    +defineAdaptation()
    +defineShape()
    +generateParticles()
    +definePhysicalModel()
}
class BaseParticleGenerator
BaseParticleGenerator <|-- SurfaceParticleGenerator
class SPHAdaptation
class BaseParticles
class VolumetricParticles
class SurfaceParticles
BaseParticles <|-- VolumetricParticles
BaseParticles <|-- SurfaceParticles
VolumetricParticles <- LatticeParticleGenerator 
SurfaceParticles <- SurfaceParticleGenerator
BaseParticleGenerator <|-- LatticeParticleGenerator
LatticeParticleGenerator <|-- ThickSurfaceParticleGenerator
SurfaceParticles <- ThickSurfaceParticleGenerator 
SPHBody *-- Shape
SPHBody *-- BaseParticles
SPHBody *-- BasePhysicalModel
SPHBody *-- SPHAdaptation
SPHBody <|-- RealBody
SPHBody <|-- ObserverBody
BasePhysicalModel *-- BaseMaterial
@enduml